# Dependencies
#markdown:         redcarpet
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Votre Coach Web'
tagline:          'Avec vous pour développer votre visibilité'
description:      'Accompagnement en réseaux sociaux et e-commerce'
url:              http://votrecoachweb.com
baseurl:          /

author:
  name:           'Bertrand Soulier'
  url:            https://twitter.com/BertrandSoulier

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://bertrandsoulier.github.io/votrecoachweb.github.io/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  
sass:
  sass_dir:          _sass
  style:            :compressed